version: '3.7'

services:

  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    volumes:
      - './flask:/usr/src/app/'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/jeopardy
      - DATABASE_TEST_URL=postgresql://postgres:postgres@postgres:5432/jeopardy_test
    depends_on:
      - postgres

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-prod
    ports:
      - 80:80
    depends_on:
      - flask

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - 6379:6379
